In [40]:
import numpy as np
import root_numpy as rnp

In [1]:
fnames_numu =[]
fnames_nue = []
for i in range(1,101):
    fnames_numu.append("aafiles/numu_files/Xy_numu_"+str(i)+"_sel5_doms.npz")
    fnames_nue.append("aafiles/nue_files/Xy_nue_"+str(i)+"_sel5_doms.npz")

In [2]:
fnames_numu

['aafiles/numu_files/Xy_numu_1_sel5_doms.npz',
 'aafiles/numu_files/Xy_numu_2_sel5_doms.npz',
 'aafiles/numu_files/Xy_numu_3_sel5_doms.npz',
 'aafiles/numu_files/Xy_numu_4_sel5_doms.npz',
 'aafiles/numu_files/Xy_numu_5_sel5_doms.npz',
 'aafiles/numu_files/Xy_numu_6_sel5_doms.npz',
 'aafiles/numu_files/Xy_numu_7_sel5_doms.npz',
 'aafiles/numu_files/Xy_numu_8_sel5_doms.npz',
 'aafiles/numu_files/Xy_numu_9_sel5_doms.npz',
 'aafiles/numu_files/Xy_numu_10_sel5_doms.npz',
 'aafiles/numu_files/Xy_numu_11_sel5_doms.npz',
 'aafiles/numu_files/Xy_numu_12_sel5_doms.npz',
 'aafiles/numu_files/Xy_numu_13_sel5_doms.npz',
 'aafiles/numu_files/Xy_numu_14_sel5_doms.npz',
 'aafiles/numu_files/Xy_numu_15_sel5_doms.npz',
 'aafiles/numu_files/Xy_numu_16_sel5_doms.npz',
 'aafiles/numu_files/Xy_numu_17_sel5_doms.npz',
 'aafiles/numu_files/Xy_numu_18_sel5_doms.npz',
 'aafiles/numu_files/Xy_numu_19_sel5_doms.npz',
 'aafiles/numu_files/Xy_numu_20_sel5_doms.npz',
 'aafiles/numu_files/Xy_numu_21_sel5_doms.npz',
 

In [31]:
shapes_numu = []
for fname in fnames_numu:
    shapes_numu.append(np.load(fname)["y"].shape)
shapes_numu = np.asarray(shapes_numu).ravel()

In [61]:
np.sort(np.unique(shapes_numu,return_index=True)[1])

array([ 0,  1,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       20, 21, 22, 23, 25, 26, 27, 28, 32, 33, 34, 35, 36, 37, 38, 40, 41,
       42, 43, 45, 46, 47, 48, 50, 51, 53, 54, 55, 56, 58, 61, 62, 63, 67,
       73, 75, 76, 78, 80, 81, 84, 87, 90, 92, 95, 96, 97, 98])

In [62]:
shapes_nue = []
for fname in fnames_nue:
    shapes_nue.append(np.load(fname)["y"].shape)
shapes_nue = np.asarray(shapes_nue).ravel()
np.sort(np.unique(shapes_nue, return_index=True)[1])


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 22, 23, 25, 26, 27, 28, 30, 31, 32, 33, 34, 35, 36, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 53, 54, 56, 57, 60, 61, 62, 64, 65, 66, 67,
       71, 73, 74, 76, 82, 84, 86, 87, 88, 90, 92, 94])

In [38]:
numu_aa = []
for i in range(1,101):
    numu_aa.append("aafiles/numu_files/numu_st_JTE_aa/km3_v4_numucc_"+str(i)+".evt.JTE.aa.root")

In [77]:
numu_aa

['aafiles/numu_files/numu_st_JTE_aa/km3_v4_numucc_1.evt.JTE.aa.root',
 'aafiles/numu_files/numu_st_JTE_aa/km3_v4_numucc_2.evt.JTE.aa.root',
 'aafiles/numu_files/numu_st_JTE_aa/km3_v4_numucc_3.evt.JTE.aa.root',
 'aafiles/numu_files/numu_st_JTE_aa/km3_v4_numucc_4.evt.JTE.aa.root',
 'aafiles/numu_files/numu_st_JTE_aa/km3_v4_numucc_5.evt.JTE.aa.root',
 'aafiles/numu_files/numu_st_JTE_aa/km3_v4_numucc_6.evt.JTE.aa.root',
 'aafiles/numu_files/numu_st_JTE_aa/km3_v4_numucc_7.evt.JTE.aa.root',
 'aafiles/numu_files/numu_st_JTE_aa/km3_v4_numucc_8.evt.JTE.aa.root',
 'aafiles/numu_files/numu_st_JTE_aa/km3_v4_numucc_9.evt.JTE.aa.root',
 'aafiles/numu_files/numu_st_JTE_aa/km3_v4_numucc_10.evt.JTE.aa.root',
 'aafiles/numu_files/numu_st_JTE_aa/km3_v4_numucc_11.evt.JTE.aa.root',
 'aafiles/numu_files/numu_st_JTE_aa/km3_v4_numucc_12.evt.JTE.aa.root',
 'aafiles/numu_files/numu_st_JTE_aa/km3_v4_numucc_13.evt.JTE.aa.root',
 'aafiles/numu_files/numu_st_JTE_aa/km3_v4_numucc_14.evt.JTE.aa.root',
 'aafiles/numu_

In [49]:
aa_numu = []
for i,fil in enumerate(numu_aa):
    print("File %d"%(i+1))
    aa_numu.append(rnp.root2array(fil, treename="E", branches="Evt.hits.channel_id"))
aa_numu = np.asarray(aa_numu)

File 1
File 2
File 3
File 4
File 5
File 6
File 7
File 8
File 9
File 10
File 11
File 12
File 13
File 14
File 15
File 16
File 17
File 18
File 19
File 20
File 21
File 22
File 23
File 24
File 25
File 26
File 27
File 28
File 29
File 30
File 31
File 32
File 33
File 34
File 35
File 36
File 37
File 38
File 39
File 40
File 41
File 42
File 43
File 44
File 45
File 46
File 47
File 48
File 49
File 50
File 51
File 52
File 53
File 54
File 55
File 56
File 57
File 58
File 59
File 60
File 61
File 62
File 63
File 64
File 65
File 66
File 67
File 68
File 69
File 70
File 71
File 72
File 73
File 74
File 75
File 76
File 77
File 78
File 79
File 80
File 81
File 82
File 83
File 84
File 85
File 86
File 87
File 88
File 89
File 90
File 91
File 92
File 93
File 94
File 95
File 96
File 97
File 98
File 99
File 100


In [64]:
nue_aa = []
for i in range(1,101):
    nue_aa.append("aafiles/nue_files/nue_st_JTE_aa/km3_v4_nuecc_"+str(i)+".evt.JTE.aa.root")

In [65]:
nue_aa

['aafiles/nue_files/nue_st_JTE_aa/km3_v4_nuecc_1.evt.JTE.aa.root',
 'aafiles/nue_files/nue_st_JTE_aa/km3_v4_nuecc_2.evt.JTE.aa.root',
 'aafiles/nue_files/nue_st_JTE_aa/km3_v4_nuecc_3.evt.JTE.aa.root',
 'aafiles/nue_files/nue_st_JTE_aa/km3_v4_nuecc_4.evt.JTE.aa.root',
 'aafiles/nue_files/nue_st_JTE_aa/km3_v4_nuecc_5.evt.JTE.aa.root',
 'aafiles/nue_files/nue_st_JTE_aa/km3_v4_nuecc_6.evt.JTE.aa.root',
 'aafiles/nue_files/nue_st_JTE_aa/km3_v4_nuecc_7.evt.JTE.aa.root',
 'aafiles/nue_files/nue_st_JTE_aa/km3_v4_nuecc_8.evt.JTE.aa.root',
 'aafiles/nue_files/nue_st_JTE_aa/km3_v4_nuecc_9.evt.JTE.aa.root',
 'aafiles/nue_files/nue_st_JTE_aa/km3_v4_nuecc_10.evt.JTE.aa.root',
 'aafiles/nue_files/nue_st_JTE_aa/km3_v4_nuecc_11.evt.JTE.aa.root',
 'aafiles/nue_files/nue_st_JTE_aa/km3_v4_nuecc_12.evt.JTE.aa.root',
 'aafiles/nue_files/nue_st_JTE_aa/km3_v4_nuecc_13.evt.JTE.aa.root',
 'aafiles/nue_files/nue_st_JTE_aa/km3_v4_nuecc_14.evt.JTE.aa.root',
 'aafiles/nue_files/nue_st_JTE_aa/km3_v4_nuecc_15.evt.JTE

In [67]:
aa_nue = []
for i,fil in enumerate(nue_aa):
    print("File %d"%(i+1))
    aa_nue.append(rnp.root2array(fil, treename="E", branches="Evt.hits.channel_id").shape[0])
aa_nue = np.asarray(aa_nue)

File 1
File 2
File 3
File 4
File 5
File 6
File 7
File 8
File 9
File 10
File 11
File 12
File 13
File 14
File 15
File 16
File 17
File 18
File 19
File 20
File 21
File 22
File 23
File 24
File 25
File 26
File 27
File 28
File 29
File 30
File 31
File 32
File 33
File 34
File 35
File 36
File 37
File 38
File 39
File 40
File 41
File 42
File 43
File 44
File 45
File 46
File 47
File 48
File 49
File 50
File 51
File 52
File 53
File 54
File 55
File 56
File 57
File 58
File 59
File 60
File 61
File 62
File 63
File 64
File 65
File 66
File 67
File 68
File 69
File 70
File 71
File 72
File 73
File 74
File 75
File 76
File 77
File 78
File 79
File 80
File 81
File 82
File 83
File 84
File 85
File 86
File 87
File 88
File 89
File 90
File 91
File 92
File 93
File 94
File 95
File 96
File 97
File 98
File 99
File 100


In [69]:
unique_nue_files = np.sort(np.unique(aa_nue, return_index=True)[1])

In [72]:
unique_nue_files

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 15, 16, 17, 18,
       20, 21, 22, 24, 25, 26, 27, 28, 30, 31, 33, 34, 35, 36, 37, 38, 40,
       41, 43, 44, 45, 46, 47, 51, 52, 54, 55, 56, 58, 60, 61, 64, 65, 67,
       70, 71, 72, 75, 80, 82, 83, 84, 85, 86, 87, 91, 93, 98])

In [59]:
unique_numu_files = np.sort(np.unique(shapes_aa_numu, return_index=True)[1])

In [84]:
unique_numu_files+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       21, 22, 23, 24, 26, 27, 28, 29, 31, 34, 36, 37, 38, 39, 41, 42, 43,
       44, 46, 48, 49, 52, 54, 55, 56, 57, 59, 62, 67, 68, 69, 71, 74, 76,
       77, 78, 79, 81, 83, 85, 88, 93, 95, 98, 99])

In [76]:
print(unique_numu_files.size, unique_nue_files.size)

(62, 65)


In [85]:
unique_numu_files[:60]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14, 15, 16, 17,
       20, 21, 22, 23, 25, 26, 27, 28, 30, 33, 35, 36, 37, 38, 40, 41, 42,
       43, 45, 47, 48, 51, 53, 54, 55, 56, 58, 61, 66, 67, 68, 70, 73, 75,
       76, 77, 78, 80, 82, 84, 87, 92, 94])

In [86]:
unique_nue_files[:60]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 15, 16, 17, 18,
       20, 21, 22, 24, 25, 26, 27, 28, 30, 31, 33, 34, 35, 36, 37, 38, 40,
       41, 43, 44, 45, 46, 47, 51, 52, 54, 55, 56, 58, 60, 61, 64, 65, 67,
       70, 71, 72, 75, 80, 82, 83, 84, 85])