In [1]:
import ROOT
import numpy as np
import root_numpy as rnp

In [2]:
numu_file = "utilities/km3_v4_numucc_1_B.evt.aa.root"

In [103]:
nue_file = "utilities/km3_v4_nuecc_1.evt.JTE.aa.root"

In [3]:
muatm_file = " utilities/km3net_jul13_90m_muatm10T1.km3_v5r2.evt.JTE.aa.root"

In [ ]:
ch_id = rnp.root2array(filename, treename="E", branches="Evt.hits.channel_id")
dom_id = rnp.root2array(filename, treename="E", branches="Evt.hits.dom_id")
trig = rnp.root2array(filename, treename= "E", branches="Evt.hits.trig")
t = rnp.root2array(filename, treename="E", branches="Evt.hits.t")
times = np.asarray([t[evt][trig[evt]==True] for evt in range(t.size)])

In [4]:
def load_directions(fname):
    trk_type = rnp.root2array(fname, treename="E", branches="Evt.mc_trks.type")
    trk_dir_x = rnp.root2array(fname, treename="E", branches="Evt.mc_trks.dir.x")
    trk_dir_y = rnp.root2array(fname, treename="E", branches="Evt.mc_trks.dir.y")
    trk_dir_z = rnp.root2array(fname, treename="E", branches="Evt.mc_trks.dir.z")
    return trk_type, trk_dir_x, trk_dir_y, trk_dir_z

In [6]:
trk_type_numu, trk_dir_x_numu, trk_dir_y_numu, trk_dir_z_numu = load_directions(numu_file)

In [41]:
trk_type_muatm, trk_dir_x_muatm, trk_dir_y_muatm, trk_dir_z_muatm = load_directions(muatm_file)

In [7]:
def sel_mu_trk(trk_dir, trk_type, part_code):
    return  np.asarray([trk_dir[evt][trk_type[evt]==part_code][0] for evt in range(trk_type.shape[0])])

In [10]:
mu_trk_dir_x = sel_mu_trk(trk_dir_x_numu, trk_type_numu, 5)
mu_trk_dir_y = sel_mu_trk(trk_dir_y_numu, trk_type_numu, 5)
mu_trk_dir_z = sel_mu_trk(trk_dir_z_numu, trk_type_numu, 5)

In [46]:
mu_trk_dir_x_muatm = sel_mu_trk(trk_dir_x_muatm, trk_type_muatm, -13)
mu_trk_dir_y_muatm = sel_mu_trk(trk_dir_y_muatm, trk_type_muatm, -13)
mu_trk_dir_z_muatm = sel_mu_trk(trk_dir_z_muatm, trk_type_muatm, -13)

In [32]:
for evt in range(mu_trk_dir_x.shape[0]):
    print(mu_trk_dir_x[evt]*mu_trk_dir_x[evt] + mu_trk_dir_y[evt]*mu_trk_dir_y[evt] + mu_trk_dir_z[evt]*mu_trk_dir_z[evt])

1.00000053887
1.00000027712
0.999999732198
0.999999428677
1.00000027035
0.999999366489
0.999999379921
0.999999878666
1.00000009246
0.999999621189
1.00000099845
1.00000087904
1.00000015912
0.999998752734
1.00000037425
0.999998879114
1.0000009953
0.999999020874
1.00000104512
1.0000008062
0.999999904688
0.999999215401
1.00000079555
0.999999776681
1.00000048612
1.00000061738
0.999999050139
0.999999099045
1.00000006945
1.00000108024
1.00000039767
0.999999251922
0.999999788702
0.999998755331
1.00000093107
1.00000027928
1.00000020735
0.999999826298
0.999999836369
0.999999642291
1.00000092993
0.999999457379
0.999999933357
0.999999763706
0.999999273281
1.00000017085
1.00000033366
1.00000100672
0.999999480686
1.00000102798
1.0000006431
0.999998951146
1.00000020485
0.99999989999
1.00000025727
1.00000038502
0.999999585425
1.0000001723
0.999999792105
0.999999371435
0.999999238286
1.00000088791
0.999999465054
0.99999951529
0.99999946685
0.99999895457
0.999999685746
1.000000666
1.00000006286
1.000000

In [47]:
print(np.min(mu_trk_dir_z), np.max(mu_trk_dir_z), np.min(mu_trk_dir_z_muatm), np.max(mu_trk_dir_z_muatm))

(-0.99727900000000003, 0.99950600000000001, -0.99997000000000003, -0.26177299999999998)


In [38]:
np.degrees(np.arccos(-0.99997000000000003))

179.55618769074044

In [37]:
np.degrees(np.arccos(-0.26177299999999998))

105.17529173472089

In [72]:
np.degrees(np.arccos(mu_trk_dir_z[np.where(np.logical_and(mu_trk_dir_z>=-0.16, mu_trk_dir_z<=0.16))[0]]))

array([ 91.19046277,  87.49944871,  84.3538784 ,  95.66598535,
        97.77573648,  85.49201672,  90.6465966 ,  87.39386234,
        90.46066303,  85.19912853,  88.80541104,  82.95712739,
        90.11837316,  85.71411872,  88.77704332,  86.48458948,
        87.37407467,  84.05285377,  85.4702339 ,  83.06755444,
        81.36072958,  96.34436977,  98.06167638,  92.26870352,
        91.42887566,  83.83073793,  83.64473449,  81.40390235,
        87.74431277,  85.06520357,  98.23942726,  84.63230339,
        83.20507589,  94.82530835,  89.20843363,  92.20110037,
        84.97910706,  97.58737645,  96.27340891,  89.70440976,
        93.34229648,  93.7336284 ,  87.47237905,  85.73985878,
        95.52016086,  90.36377335,  92.84602025,  85.48667166,
        81.62774295,  94.79471926,  82.31278811,  98.50026584,
        91.14731007,  94.30145214,  81.03529532,  93.97745831,
        97.58032468,  96.22372478,  90.67495989,  81.30016347,
        93.41553322,  84.34840874,  94.74786082,  84.62

In [74]:
np.degrees(np.arccos(mu_trk_dir_z[np.where(np.logical_and(mu_trk_dir_z>=0.3, mu_trk_dir_z<=zmax))[0]]))

array([ 23.68411448,  19.93063465,  41.10203879,  49.88004484,
        68.61992385,  61.91674856,  40.71145049,  47.5074761 ,
        32.58429974,  64.04666319,  65.28234498,  69.25416863,
        66.70383668,  71.21971149,  68.78682166,  46.0918751 ,
        29.21198603,   8.68251544,  33.94746016,  44.15038874,
        40.92549965,  55.91079301,  61.41271535,  34.80945684,
        50.19207204,  71.20954421,  35.98420512,  43.34307111,
        21.99691857,  72.21012771,   6.93631397,  12.90774687,
        38.97695666,  65.30189661,  51.22784421,  63.50741439,
        20.99878912,  70.31054377,  71.9972284 ,  71.98614292,
        70.10332394,  64.03047666,  55.76205508,  38.14946732,
        26.16797572,  52.04720776,  65.63965735,  53.79259184,
        47.15260595,  26.88486648,  67.36228148,  46.64205667,
        46.04986977,  26.73700567,  36.95175268,  34.19852949,
        69.80984102,  44.81932774,  71.42649521,  23.91681727,
        65.80000213,  72.51764953,  19.22270044,   1.80

In [75]:
np.where(np.logical_and(mu_trk_dir_z>=0.3, mu_trk_dir_z<=zmax))[0]

array([   0,    1,    3,    4,    5,    6,    9,   10,   11,   12,   13,
         15,   16,   17,   18,   19,   20,   21,   23,   28,   32,   36,
         41,   43,   44,   47,   48,   50,   51,   52,   53,   54,   59,
         60,   62,   68,   69,   74,   76,   77,   80,   84,   85,   88,
         90,   91,   94,   97,   98,   99,  101,  103,  104,  105,  106,
        108,  109,  112,  113,  114,  119,  121,  124,  125,  126,  127,
        131,  132,  134,  135,  136,  142,  143,  145,  146,  148,  153,
        154,  156,  157,  159,  162,  168,  172,  175,  176,  182,  188,
        191,  194,  195,  200,  201,  207,  210,  211,  213,  214,  215,
        216,  224,  230,  231,  234,  238,  242,  243,  245,  247,  248,
        254,  266,  268,  272,  274,  275,  276,  278,  279,  281,  282,
        286,  287,  290,  303,  305,  306,  309,  310,  314,  315,  324,
        325,  328,  330,  331,  332,  335,  336,  343,  347,  349,  351,
        356,  362,  364,  365,  366,  376,  377,  3

In [51]:
np.where(mu_trk_dir_z>=0)[0].shape

(872,)

In [52]:
np.where(mu_trk_dir_z<=0)[0].shape

(669,)

In [ ]:
(0.10452846326765346, -0.10452846326765355)

In [64]:
np.min(mu_trk_dir_z)

-0.99727900000000003

In [65]:
np.max(mu_trk_dir_z)

0.99950600000000001

In [50]:
zmin = 0.9
zmax= 1.0

In [57]:
dir_greater_than_minimum = np.where(mu_trk_dir_z>= zmin)[0]

In [58]:
dir_greater_than_minimum

array([   0,    1,   21,   51,   53,   54,   69,  114,  124,  125,  127,
        134,  148,  157,  216,  254,  275,  286,  303,  315,  351,  362,
        376,  396,  401,  414,  432,  436,  462,  520,  581,  600,  604,
        616,  620,  652,  662,  694,  729,  747,  768,  856,  913,  930,
        954,  958,  967,  971,  985, 1051, 1060, 1063, 1092, 1113, 1165,
       1281, 1302, 1306, 1319, 1353, 1364, 1368, 1388, 1391, 1409, 1445,
       1459, 1466, 1485, 1488, 1491, 1502, 1525, 1539, 1540])

In [63]:
mu_trk_dir_z[dir_greater_than_minimum]

array([ 0.915774,  0.940106,  0.98854 ,  0.927204,  0.992681,  0.974731,
        0.933588,  0.914135,  0.944246,  0.999506,  0.912594,  0.925574,
        0.971521,  0.990968,  0.96889 ,  0.913793,  0.916399,  0.936952,
        0.990615,  0.947171,  0.980978,  0.95208 ,  0.996372,  0.989135,
        0.976199,  0.905289,  0.935697,  0.960103,  0.97413 ,  0.906306,
        0.921042,  0.957935,  0.976043,  0.980573,  0.993273,  0.969205,
        0.919912,  0.921781,  0.949666,  0.933234,  0.905884,  0.967951,
        0.931842,  0.928712,  0.926848,  0.979382,  0.904132,  0.914253,
        0.917906,  0.997742,  0.960454,  0.921798,  0.991364,  0.973708,
        0.941177,  0.975758,  0.940808,  0.978415,  0.922913,  0.939892,
        0.992854,  0.995654,  0.930152,  0.982006,  0.930101,  0.973408,
        0.986514,  0.954022,  0.985995,  0.996166,  0.983154,  0.98037 ,
        0.933495,  0.987213,  0.987213])

In [66]:
less_than_max = np.where(mu_trk_dir_z[dir_greater_than_minimum]<=zmax)[0]

In [67]:
less_than_max

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74])

In [51]:
np.where(mu_trk_dir_z[np.where(mu_trk_dir_z>=-zmin)[0]]<=zmax)[0]

In [54]:
mu_trk_dir_z[sel]

array([ 0.915774,  0.940106,  0.208183, ..., -0.701322,  0.983154,
        0.558694])

In [35]:
mu_trk_dir_z[7]

False

In [105]:
import select_evt_direction
reload(select_evt_direction)

<module 'select_evt_direction' from 'select_evt_direction.py'>

In [106]:
upgoing_numu_indx, downgoing_numu_indx = select_evt_direction.sel_numu_up_down(numu_file,"numu")

 reload


In [107]:
upgoing_numu_indx.shape

(656,)

In [108]:
downgoing_numu_indx.shape

(455,)

In [109]:
upgoing_nue_indx, downgoing_nue_indx = select_evt_direction.sel_numu_up_down(nue_file,"nue")

 reload


In [113]:
print(upgoing_nue_indx.shape, downgoing_nue_indx.shape, upgoing_nue_indx.shape[0]+downgoing_nue_indx.shape[0])

((465,), (392,), 857)


In [6]:
numu_file

'utilities/km3_v4_numucc_1_B.evt.aa.root'

In [7]:

from load_trees import load_trees

In [18]:
ch_id = rnp.root2array(numu_file, treename="E", branches="Evt.hits.channel_id")
dom_id = rnp.root2array(numu_file, treename="E", branches="Evt.hits.dom_id")
trig = rnp.root2array(numu_file, treename= "E", branches="Evt.hits.trig")
t = rnp.root2array(numu_file, treename="E", branches="Evt.hits.t")
times = np.asarray([t[evt][trig[evt]==True] for evt in range(t.size)])

In [19]:
times[0]

array([ 50000098.,  50000104.,  49999943.,  49999943.,  49999944.,
        49999944.,  49999945.,  49999945.,  49999946.,  49999948.,
        49999948.,  49999833.,  49999833.,  49999836.,  49999836.,
        49999840.,  49999704.,  49999710.,  49999712.,  49999341.,
        49999346.,  49999349.])

In [20]:
dom_id=np.asarray([dom_id[evt][trig[evt]==1] for evt in range(dom_id.shape[0])])

In [33]:
dom_id[0].shape

(22,)

In [35]:
times[0].shape

(22,)

In [36]:
from timeslices import tslices

In [38]:
timeslice = tslices(times,times)

(49993098.0, 49993098.0, 50004225.0, 50004225.0, 49993098.0, 50004225.0)


In [54]:
timeslice[30:70]

array([ 49997598.,  49997748.,  49997898.,  49998048.,  49998198.,
        49998348.,  49998498.,  49998648.,  49998798.,  49998948.,
        49999098.,  49999248.,  49999398.,  49999548.,  49999698.,
        49999848.,  49999998.,  50000148.,  50000298.,  50000448.,
        50000598.,  50000748.,  50000898.,  50001048.,  50001198.,
        50001348.,  50001498.,  50001648.,  50001798.,  50001948.,
        50002098.,  50002248.,  50002398.,  50002548.,  50002698.,
        50002848.,  50002998.,  50003148.,  50003298.,  50003448.])

In [93]:
for evt in range(1000,1500):
    print(np.histogram(times[evt], bins=timeslices)[0])

[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 17  8  2  0  1  2  0  0  0  0  0
  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0]
[ 0  0  0  7 42 42 42 54 37 30 34 22 49 12 21 57 47 31 26 11 13 40 18 25 46
 27 44 13  6 29  9  2 19 20  4  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0]
[ 0  0  0  0  0  2  0  0  0  0  2 39 22 18 14  8 28  0  0  9 15 38 25  5  7
 16  0  0  0  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 25  6  2
 20  9  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  0  0
  0  0  0  0  0  0  0  0]
[ 0  3  0 37 25  9  9 12  4 12  2  4  7  0  0  0  2 11  6  2  0  5  2 23  3
  2  4  0 15  2  0  0  2  4 53 86 35 31  8  1  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0]
[ 0  0  0  0  0  0  0  2  0  0  0  0  0 45 33 21 21  2  5  2  0 30 17 11 12
 15  7  2  0  0  2  0  0  2  0  0 

  0  0  0  0  0  0  0  0]
[ 0  0  0  0  0  0  0  0  0  0  0  0  5 18 29 23 61 40 15 16  5  4  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0]
[ 0  0  0  0  0  0  0  0  0  0  0  2  0  0  1  1  0  0  0  0 16  9  2  5  4
  0  0  2  0  0  3  0  0  0  0  0  0  4  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0]
[  0  68  68  59  89  85  79 116 145 101 143 127 125  89  88  97  88  68
 127 135  84 137 221 266 234 149 165 140 107  39 107  34  35  33  29  37
  21   6   7   2   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0]
[  0   0   0   0   2   0   2   0  18 105 156 173 202 227 198 135 166 249
 341 410 414 362 232 128  98  45  15   4   4   4   4   2   0   0   2   0
   0   0   0   2   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0]
[ 0  0  0  0  0  2  0  0  0  0  0  2  0  2  3  0  0 15 21 30 33 62 50 84 71
 59 18 17  2  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  

In [94]:
timeslices = np.arange(start=49997200.0, stop=50003000.0+200, step=100,)

In [95]:
timeslices.shape

(60,)